services:
  web-monitor:
    image: fengyu666/web-monitor:latest
    container_name: web-monitor
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data.db:/app/data.db
      - ./data.db-journal:/app/data.db-journal
      - ./data.db-wal:/app/data.db-wal
      - ./data.db-shm:/app/data.db-shm
      - ./logs:/app/logs
      - ./cookie_cache.json:/app/cookie_cache.json
    environment:
      - TZ=Asia/Shanghai
