services:
  web-monitor:
    image: fengyu666/webmoniter:latest
    container_name: webmoniter
    restart: unless-stopped
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
